### ISSUE TITLE
Style Event Listing on public page

### ISSUE THREAD

**Issue by jakemoves** [jakemoves/cohort-server-v1#9]
- make it look nice
- make sure it is not shown after the user is checked in

**Comment by jakemoves** [comment]
Notes:
- text in general should be more compact, use Chrome Mobile preview from inspector: we want ~2-3 events to fit on screen
- header ('upcoming FluxDelux Events') should not line-break at mobile size

**Comment by jakemoves** [comment]
Looking better...
- please fix weird empty space on left of events -- I like the round box though!
- some signup buttons display yellow text, it's not very readable 
- make the sign-up buttons a bit wider
- get rid of long empty space between event listing and footer
- line spacing is super large when footer text ( copyright notice) wraps

**Comment by helloCaller** [comment]
haven't come across the yellow text on signup button issue (the styling for which is a bootstrap btn-warning), let me know in what context it happens. Everything else has been addressed.

**Comment by jakemoves** [comment]
Awesome. Did you deploy to the server & test there? (Make sure you change the baseUrl environment variable in admin.js and fluxdelux.js)
